### ISSUE TITLE
Outdated reduceOperandTable in ReduceTaskSchedule

### ISSUE THREAD

**Issue by vsilaev** [beehive-lab/TornadoVM#149]
**Describe the bug**
After commit https://github.com/beehive-lab/TornadoVM/commit/32eda09017854d3bbfc125f49a42e77b3e4d5646 in [ReduceTaskSchedule](https://github.com/beehive-lab/TornadoVM/blob/develop/runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/ReduceTaskSchedule.java) the field `reduceOperandTable` has no purpose.

**How To Reproduce**
This is just a code improvement

**Expected behavior**

Any usage of variable is completely removed

**Computing system setup (please complete the following information):**
OS / Driver independent
https://github.com/beehive-lab/TornadoVM/commit/32eda09017854d3bbfc125f49a42e77b3e4d5646 

**Additional context**
After removing code that saves several task id's into `reduceOperandTable` it no longer serves any purpose - while the sole purpose of this variable is to keep track of that lists with size() > 1 and execute `forceCopyIn` if found. Effectively, after commit the list size is always 1 if the list is present.

**Comment by stratika** [comment]
Thanks @vsilaev, you are right. At this stage, the hashmap `reduceOperandTable` is not utilized. This functionality exists because it is a work-in-progress for future supported cases. For example, support for multiple reductions within the same task. I will close this PR, if you need any clarification, feel free to reopen it.
