### ISSUE TITLE
how to specific -Xmx to set a bigger allowed size

### ISSUE THREAD

**Issue by quantrpeter** [beehive-lab/TornadoVM#262]
/home/peter/workspace/TornadoVM-example/target/classes>tornado --jvm Xmx1400M hk.quantr.tornadovm.example.Init
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
Error: Could not find or load main class Xmx1400M
Caused by: java.lang.ClassNotFoundException: Xmx1400M

thanks

**Comment by stratika** [comment]
Hi @quantrpeter, can you try to pass the JVM options as follows?
```bash
tornado --jvm="-Xmx1400M" hk.quantr.tornadovm.example.Init
```

**Comment by stratika** [comment]
I quote the message, as reported in `tornado --help`:
```bash
--jvm JVM_OPTIONS, -J JVM_OPTIONS
                        Pass Java options to the JVM. Use without spaces: e.g., --jvm="-Xms10g" or -J"-Xms10g"
```

So, better try without spaces and also in case you want to also use [TornadoVM Flags](https://tornadovm.readthedocs.io/en/latest/flags.html) you can combine them together with the JVM options in the `--jvm` field. 

Note that the TornadoVM Flags that start with `-D` should be specified in the `--jvm` field as any other JVM option. While the flags that start with `--`, such as `--printKernel` or `--threadInfo` can be directly added in the command line because they are identified by the tornado script.
