### ISSUE TITLE
Running TornadoVM version v0.15.2 on AWS F1 instances

### ISSUE THREAD

**Issue by ShAlireza** [beehive-lab/TornadoVM#284]
---------------------------------------------------------------------

### Describe the bug 
I don't know if this is a bug or a problem from my side, but I just followed the documents on [this link](https://tornadovm.readthedocs.io/en/latest/cloud.html)

When I try to run the mentioned example in the document, I get the following error:

<img width="1129" alt="Screenshot 2023-11-23 at 2 04 57 PM" src="https://github.com/beehive-lab/TornadoVM/assets/45388177/ae70c707-8df4-4dd2-ba76-8664421cd98e">

### How To Reproduce

Just follow the documents in the mentioned link and run the example.

### Expected behavior 

To program the FPGA and run the code successfully.

### Computing system setup (please complete the following information):
 - OS: CentOS 7 (AMI 1.10.5)
 - v0.15.2 release
 - Vitis version: 2020.2

---------------------------------------------------------------------

**Comment by stratika** [comment]
Hello @ShAlireza, the documentation uses a different AMI image. So, it may have a different behaviour. To my understanding, if you use a different AMI image, you should also be careful with the version of the `aws-fpga` repository that you use. Also, you are trying version `v0.15.2`. Is there any particular reason of staying with the release version? I am asking because we are looking at a fix for `FPGA DEV AMI: 1.12.2` and it will be provided in the master branch.

**Comment by ShAlireza** [comment]
Thanks for your reply @stratika.

There are only two AMI versions available on AWS: 1.12.2 and 1.10.5. I was just testing whether the document examples work on older versions or not. In this process, I encountered the mentioned error and wondered about the reason for this issue.

Great! So I will wait for the fix on AMI 1.12.2.

Cheers!
