### ISSUE TITLE
No more inferred moves?

### ISSUE THREAD

**Issue by jay-tux** [beehive-lab/TornadoVM#599]
Hi!

I was just reading your original Tornado paper (from ManLang '18), where it is mentioned that Tornado(VM) automatically infers which data moves need happening (see code below). What happened to the `TaskSchedule` API?

```java
TaskSchedule s = new TaskSchedule("s0")
    .task("t0", this::add, input0, input1, output0)
    .streamOut(output0).execute()
```
(code sample from the ManLang '18 paper; a very similar sample is found in the VEE '19 paper)

Is it still possible to have Tornado(VM) infer the copies from the arguments, or do we always need to specify these explicitly? This was one of the bigger selling points to me, the guaranteed memory consistency...

**Comment by jjfumero** [comment]
Hi @jay-tux . The API you showed is the old one. TornadoVM has evolved to a new explicit API since version 0.15:

https://tornadovm.readthedocs.io/en/latest/programming.html 

From v0.15, we require all data to be explicitly tagged. We made this decision because for many users, this was confusing (where is my data?). So, we make it explicit. However, we rethink this  frequently, In the future I would like to remove completely the need to pass any data as stream-in or out.

**Comment by jay-tux** [comment]
Thanks for the reply!
