### ISSUE TITLE
Can't compile internal While loop or For loop with break

### ISSUE THREAD

**Issue by AlexeyPirogov** [beehive-lab/TornadoVM#77]
Hi,

I used Aparapi before for GPU calculations [Java on GPU: Pricing options with Monte Carlo simulation](https://medium.com/@pirogov.alexey/java-on-gpu-pricing-options-with-monte-carlo-simulation-6350a1fe1efe).
I was excited to hear about Torando VM and wanted to repeat my calculations on FPGA.

I noticed an issue when moving from Aparapi to Tornado VM.
I have a Monte Carlo simulation (n elements with m calculations/simulations per each).
Seems that Tornado can't compile simulations with _breaks_ (_while_ loop or _for_ loop with break).

Maybe Tornado thinks that I modify incoming arrays, but this isn't the case.

Do you have any suggestion about how to fix or debug this issue, please?

```
public static void mapCalcMc(float[] arrS, float[] arrB, int iterPerElement, int logicIterNum, float[] results) {
        int arrLength = arrS.length;
        int currentIter = 0;

        for (@Parallel int i = 0; i < arrLength; i++) {
            for (@Parallel int j = 0; j < iterPerElement; j++) {
                int k = 0;
                float curA = arrS[i];
                float b = arrB[i];
                while (k < logicIterNum
                        && curA > b//Condition that can't be compiled
                ) {
                    k++;
                }

                results[currentIter] = 0.0f;
                currentIter++;
            }
        }
    }
```

UPD:
1. I run code on AMD 4Gb GPU locally. Tornado works for me both on CPU and GPU with other tasks.
2. Code above is "Minimum Breaking Example". I tried to remove all non-essential logic.
3. Here is the code to trigger task:
```
TaskSchedule task = new TaskSchedule("s0")
    .task("map", MonteCarloTornadoGPU::mapCalcMc, new float[10], new float[10],
      10,
      100, // It looks crazy but if I replace 100 wit 10 code works. 
           // This param is used for number of iterations in no-op loop 
       new float[100])
     .streamOut(gpuInterimMapResults);
task.execute();
```
I found a strange behavior, when I increase number of iterations in no-op while loop, app crashes (see comment to task code).

Attaching kernel out.
[kernel.txt](https://github.com/beehive-lab/TornadoVM/files/6243915/kernel.txt)

**Comment by jjfumero** [comment]
@AlexeyPirogov, thank you for the report. TornadoVM can handle `break` and `continue`:

Unittests here: https://github.com/beehive-lab/TornadoVM/blob/master/unittests/src/main/java/uk/ac/manchester/tornado/unittests/loops/TestLoops.java#L578-L585

What I think is happening is that the codegen is failing due to complex control flow (we are actually fixing similar cases). Could you please report the generated OpenCL code? You can use `--printKernel` to print the OpenCL generated code. I think it could be a missing closing bracket `}`.

Additionally, if you are running on NVIDIA, you could try the PTX backend instead:

``` bash
# compile TornadoVM with PTX and OpenCL 
make BACKEND=PTX,OpenCL
```

Then the PTX will be the default one.

**Comment by stratika** [comment]
Thanks @AlexeyPirogov for the report. It is not very clear for which device do you see this problem. Is it an FPGA? If yes, does the TornadoVM program work on GPUs?

**Comment by gigiblender** [comment]
Hi @AlexeyPirogov,

The `while` loop in the code snippet provided is removed during a compilation phase since it has no side effects. The variable `k` is not used anywhere but inside the loop. 

Also, a side remark is that the body of the `@Parallel` annotated loops will run with multiple threads. Using a separate `induction variable`, in this case, `currentIter` will cause a race condition. Therefore, 
```
    results[currentIter] = 0.0f;
    currentIter++;
```
could be replaced with something along the lines:
```
results[i * arrLength + j]  = 0.0f;
```

**Comment by AlexeyPirogov** [comment]
I'm sorry, seems I didn't provide enough information in my original post.
I extended post with extra details.

**Comment by stratika** [comment]
Thanks for the update. Based on your kernel file, it seems that @jjfumero is right. There is a missing curly bracket from the kernel and results in failed compilation. We have also identified similar behaviour regarding the closing brackets, and will look at it.

**Comment by jjfumero** [comment]
Thank you @AlexeyPirogov . After looking at the generated kernel, the error is that we are missing a closing bracket. This is due to a bug in our OpenCL-IR visitor: 

https://github.com/beehive-lab/TornadoVM/blob/c10957db7b413b306651dd8b0b3d558fdd301c79/drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java 

We will fix this and let you know.
