### ISSUE TITLE
Deprecate passing local and global dimensions for tasks as a runtime flag

### ISSUE THREAD

**Issue by gigiblender** [beehive-lab/TornadoVM#92]
Currently, we can specify the local/global work for a task through a runtime flag:` <ts>.<taskName>.global/local.dims=x,x,x`, bypassing the scheduler.
Since we now have the Grid API, I think we can deprecate these options and remove the extra logic in the `TaskMetaData`.
Please note that [slambench](https://github.com/beehive-lab/kfusion-tornadovm) uses the runtime flags and needs refactoring as well.

At the suggestion of @stratika, we can also rename the `GridTask` to `GridScheduler`.

**Comment by stratika** [comment]
I agree with that. These flags were used mainly for the Ahead of Time FPGA execution. I have tested FPGAs also with the `Grid` API and they work. So, we could proceed with these change and check Slambench if it works.

**Comment by jjfumero** [comment]
IMO we should keep this flag. The reason is that the command line grid options do not require source code modifications for tasks that do not have an explicit `GridTask`.  This works for GPUs, FPGAs and multi-core. 

Additionally, other benchmark suites for TornadoVM use these flags to run on FPGAs, such as KFusion: https://github.com/beehive-lab/kfusion-tornadovm/
